### ISSUE TITLE
changing the title of the app

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/covid_prefs#10]
Can you please change the title for the following?
/**beauty_contest_1**/Guess/12/

suggestion: **bc_game**

**Comment by billuraksoy** [comment]
I believe subjects will be able to see these names right? Can you actually do this for other games as well? some of them are not that big of a deal (e.g. multiple price list) but others need to be changed (e.g. dictator).

**Comment by elifbikeosun** [comment]
I changed all the names to codes such as da/db/dc/dd for dictator1/dictator2/dictator3/dictator4, mpa/mpb for multiple_price_list_1/multiple_price_list_2 and so on.
