### ISSUE TITLE
summation task

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/covid_prefs#11]
This task has 3 min to complete. There are only 8 summation questions. I completed all of them using a calculator, I think, in about 1.5 min. 
We need to discuss this.

**Comment by billuraksoy** [comment]
We have decided to keep using this method. But in that case, we need to think about increasing the number of tasks. 8 is too few. I think we should have at least 30 or so.

**Comment by elifbikeosun** [comment]
When calculating the max amount the subjects can earn from each section, I noticed that they can earn quite a significant amount of money (almost double what they can earn from the remaining parts) if somehow they manage to solve all 30 questions correctly (which is unlikely even when using a calculator, but still). Would it be better to include something like 20 questions for each part?

**Comment by billuraksoy** [comment]
Good catch! I think 20 is fine but we should discuss this issue when we meet next time. Lets leave the discuss the label and keep it open.
