### ISSUE TITLE
overconfidence/JellyCount pic size

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/covid_prefs#16]
Can we make the size of the picture a little bigger? Say by 15% or so. (for all pictures), By the way, the first one looked especially smaller compared to the other ones.Can we make the first pic slightly bigger so that they look similarly big.

**Comment by elifbikeosun** [comment]
I increased all image sizes by about 15%. If I need to change each image size customly, I will need to restructure the code a little bit. Please let me know if this seems fine - If not, I'll go ahead and modify again.
