### ISSUE TITLE
page /i/I/1/ text edits

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/covid_prefs#22]
1. Is there a reason why we have this info on the intro screen: "You can possibly earn up to $8.45 upon completing the study." ? I suggest removing. Otherwise I would be worried about subjects anchoring toward making that amount. Also, this could have different impacts across orderings (for example, people who face dictator game first may end up acting more selfishly relative to other subjects who face the dictator game decisions later in the game or subjects who face risky decisions first may end up taking more risk etc. )

2. I suggest removing this part since it does not convey any extra info:
Consent Form
After clicking the Continue button, you will be directed to the Consent form page. Once you give consent to participate in this study, you may begin the experiment.

**Comment by elifbikeosun** [comment]
<img width="977" alt="Screen Shot 2020-10-26 at 1 45 05 PM" src="https://user-images.githubusercontent.com/64322504/97208406-7b399480-1791-11eb-911c-8724a7998a8d.png">

I was following Yariv & Snowberg (They actually put in the min, max, and expected payoffs.) I agree that this is not a great approach and may cause anchoring. This is another one of these decisions where we need to trade off between better design and comparability.

**Comment by elifbikeosun** [comment]
Deleted the information about max possible earnings.
