### ISSUE TITLE
rpa.1.player.amount_risky and rpb.1.player.amount_risky

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/covid_prefs#28]
**For rpa.1.player.amount_risky:** I invested 100 tokens so I had 100 tokens left.If the project is a success, it pays 2.5X. From the data below, it looks the project failed. So my earning is the amount that I kept to myself and did not invest. Correct? If this is correct, this is all good. 

<img width="814" alt="Screen Shot 2020-10-26 at 5 01 30 PM" src="https://user-images.githubusercontent.com/44884690/97228167-e6dd2b00-17ac-11eb-9f58-2a901507209e.png">

**For rpb.1.player.amount_risky** : I invested 100 tokens and so I had 100 tokens left. If the project is a success, it pays 3x. This is how the data looks like and it looks like the project failed. now my question is, why is my earning 0? Should it not be 100 tokens (amount I did not invest)? It is also confusing because if you look at the first subject, they invested 50 and kept 150 to self. How come their earnings are 50 tokens? It should be either 150 (project failed) or 300 (project succeeded). This may be a bug.  

<img width="804" alt="Screen Shot 2020-10-26 at 5 03 39 PM" src="https://user-images.githubusercontent.com/44884690/97228370-33286b00-17ad-11eb-93b7-43f21e6e0401.png">

**Comment by elifbikeosun** [comment]
Yes, you are right about rpa. About rpb: The endowments in rpa and rpb are different. The endowment in rpb is 100 tokens (the one that pays 3x) and the endowment in rpa is 200 tokens (the one that pays 2.5x). It seems like the screens and data is consistent with this, but please let me know if I'm missing something.

**Comment by billuraksoy** [comment]
You are right, I thought the endowment was 200 for both.
