### ISSUE TITLE
info sheet

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/covid_prefs#8]
Can you please upload the information sheet as the first page? You can copy this page from Ian's repo and just change the link and the pdf document:

https://github.com/ianchadd/rpi_3208

Here is the link that I created:  https://virtual-experimental-lab.github.io/virtual-experimental-lab.github.io/Information_sheet.pdf

**Comment by elifbikeosun** [comment]
I added the information page with slight modifications & added the consent page.
