### ISSUE TITLE
intro page

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/covid_prefs#9]
Can you please add an intro page, you can take our intro page from another study:
https://github.com/ianchadd/rpi_3208/blob/master/qsp_dg_dict_intro/templates/qsp_dg_dict_intro/introduction.html

This page should come after the information sheet. 

Feel free to edit the text for this project. We still need to make a few decisions on a few important things, so it is ok if you put a placeholder such as "to be updated".

**Comment by billuraksoy** [comment]
Edit: We need to put info about the conversation rate here and then remove this information from the instructions. Since we randomize the order, now it feels weird (for example, the very first game does not contain any info about the conversation rate but then in the second game, there is info about it). It would be cleaner if we get rid of all USD amounts from the instructions and just mention that at the very beginning in this intro page.

**Comment by elifbikeosun** [comment]
I added an introduction page & removed USD/token conversion information from random pages during the experiment. The only question that is in USD amounts is the hypothetical time inconsistency question, which I think we should keep in its current form. Please take a look to the intro page and let me know if you have any additional comments / corrections.
